"use client";

import { TriangleAlert } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Card, EmptyState, ErrorBanner, PageTitle, SuccessBanner } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { PROJECTOR_LABELS, PROJECTOR_LOCATIONS, type ProjectorLocation } from "@/lib/types";
import { cn, friendlyError } from "@/lib/utils";

interface CardRow {id:number;location:ProjectorLocation;label:string;status:"AVAILABLE"|"USED"|"DISABLED";used_at:string|null;used_by_group:number|null;used_by_user:string|null;created_at:string;version:number}
interface LogRow {log_id:number;nfc_id:number|null;zone_location:ProjectorLocation|null;group_id:number|null;user_id:string|null;action:string;status:string;created_at:string;detail:Record<string,unknown>}
interface PuzzleOption {id:number;puzzle_code:string;puzzle_location:ProjectorLocation}

export default function AdminNfcPage(){
  const supabase=useMemo(()=>supabaseBrowser(),[]);const [location,setLocation]=useState<ProjectorLocation>("B1"),[count,setCount]=useState(3),[minted,setMinted]=useState<{label:string;url:string}[]>([]);
  const [cards,setCards]=useState<CardRow[]>([]),[logs,setLogs]=useState<LogRow[]>([]),[puzzles,setPuzzles]=useState<PuzzleOption[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
  const [filter,setFilter]=useState({id:"",zone:"ALL",group:"",status:"ALL",user:"",date:""});
  const load=useCallback(async()=>{const [a,b,c]=await Promise.all([supabase.from("nfc_tokens").select("id,location,label,status,used_at,used_by_group,used_by_user,created_at,version").order("id",{ascending:false}),supabase.from("nfc_logs").select("*").order("created_at",{ascending:false}).limit(200),supabase.from("items").select("id,puzzle_code,puzzle_location").eq("type","puzzle").order("puzzle_location").order("puzzle_index")]);if(a.error||b.error||c.error)setError(friendlyError(a.error||b.error||c.error));else{setCards((a.data as CardRow[])??[]);setLogs((b.data as LogRow[])??[]);setPuzzles((c.data as PuzzleOption[])??[])}},[supabase]);
  useEffect(()=>{void load()},[load]);
  async function mint(){setBusy(true);setError(null);const response=await fetch("/api/admin/nfc",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({location,count})}),data=await response.json();setBusy(false);if(!response.ok)setError(data.error??"Generation failed.");else{setMinted(data.tokens);setNotice("NFC cards generated. Write these URLs to the cards now.");await load()}}
  async function edit(card:CardRow){const label=window.prompt("Card label:",card.label);if(label===null)return;const zone=window.prompt("Zone (B1, A3 or TF):",card.location)?.toUpperCase() as ProjectorLocation|undefined;if(!zone||!PROJECTOR_LOCATIONS.includes(zone))return;const status=window.prompt("Status (AVAILABLE, USED or DISABLED):",card.status)?.toUpperCase();if(!status)return;const reason=window.prompt("Reason for edit:");if(!reason)return;await action("fn_admin_set_nfc_card",{p_nfc_id:card.id,p_location:zone,p_label:label,p_status:status,p_expected_version:card.version,p_reason:reason},"NFC card updated.")}
  async function requirements(card:CardRow){const choices=puzzles.map(p=>`${p.id}=${p.puzzle_code}`).join(", ");const raw=window.prompt(`Required Puzzle IDs, separated by commas. Available: ${choices}`);if(!raw)return;const ids=raw.split(",").map(x=>Number(x.trim())).filter(Number.isInteger);const reason=window.prompt("Reason for requirement change:");if(!reason)return;await action("fn_admin_set_nfc_requirements",{p_nfc_id:card.id,p_puzzle_ids:ids,p_reason:reason},"Puzzle requirements updated.")}
  async function reset(card:CardRow){const reason=window.prompt("Reason for resetting this card:");if(!reason)return;if(!window.confirm("Reset this card to AVAILABLE? Existing Zone and Puzzle state will not be changed."))return;await action("fn_admin_reset_nfc",{p_nfc_id:card.id,p_reason:reason},"NFC card reset.")}
  async function revert(card:CardRow){const reason=window.prompt("Reason for reverting the activation:");if(!reason)return;if(!window.confirm("Revert the Zone activation and restore linked Puzzle pieces to COLLECTED?"))return;await action("fn_admin_revert_nfc_activation",{p_nfc_id:card.id,p_reason:reason},"Activation reverted and linked state restored.")}
  async function action(name:string,args:Record<string,unknown>,message:string){setBusy(true);setError(null);const {error:e}=await supabase.rpc(name,args);setBusy(false);if(e)setError(friendlyError(e));else{setNotice(message);await load()}}
  const filtered=cards.filter(card=>(!filter.id||String(card.id).includes(filter.id))&&(filter.zone==="ALL"||card.location===filter.zone)&&(!filter.group||String(card.used_by_group??"")===filter.group)&&(filter.status==="ALL"||card.status===filter.status)&&(!filter.user||(card.used_by_user??"").includes(filter.user))&&(!filter.date||(card.used_at??card.created_at).startsWith(filter.date)));
  return <div className="space-y-4"><PageTitle title="NFC cards & log" subtitle="Generate, configure, reset, and fully revert current-orientation cards"/><ErrorBanner message={error}/><SuccessBanner message={notice}/>
    <Card className="space-y-3"><h2 className="font-semibold">Generate secure cards</h2><div className="grid grid-cols-3 gap-2">{PROJECTOR_LOCATIONS.map(loc=><button key={loc} onClick={()=>setLocation(loc)} className={cn("btn text-sm",location===loc?"bg-brand-2 text-white":"border border-paper-300 bg-white")}>{loc}</button>)}</div><label className="label">Number of cards<input type="number" min="1" max="20" className="input mt-1" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><button disabled={busy} onClick={()=>void mint()} className="btn-primary w-full">Generate {count} card URL{count===1?"":"s"}</button></Card>
    {minted.length>0&&<Card className="space-y-2 border-2 border-amber-400"><p className="flex gap-2 text-sm font-semibold text-red-700"><TriangleAlert size={18}/>These full URLs are shown once. Write them as HTTPS URL records now.</p>{minted.map(row=><div key={row.label} className="rounded-xl bg-paper-100 p-2"><p className="text-xs font-bold">{row.label}</p><p className="break-all font-mono text-[10px]">{row.url}</p></div>)}</Card>}
    <Card className="space-y-3"><h2 className="font-semibold">Filters</h2><div className="grid grid-cols-2 gap-2"><input className="input" placeholder="NFC ID" value={filter.id} onChange={e=>setFilter({...filter,id:e.target.value})}/><select className="input" value={filter.zone} onChange={e=>setFilter({...filter,zone:e.target.value})}><option>ALL</option>{PROJECTOR_LOCATIONS.map(x=><option key={x}>{x}</option>)}</select><input className="input" placeholder="Group ID" value={filter.group} onChange={e=>setFilter({...filter,group:e.target.value})}/><select className="input" value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option>ALL</option><option>AVAILABLE</option><option>USED</option><option>DISABLED</option></select><input className="input" placeholder="User ID" value={filter.user} onChange={e=>setFilter({...filter,user:e.target.value})}/><input type="date" className="input" value={filter.date} onChange={e=>setFilter({...filter,date:e.target.value})}/></div></Card>
    {filtered.length===0?<EmptyState title="No NFC cards" message="No cards match the current filters."/>:<div className="space-y-3">{filtered.map(card=><Card key={card.id} className="space-y-3"><div className="flex items-start justify-between"><div><p className="font-black">NFC{String(card.id).padStart(2,"0")} · {card.label}</p><p className="text-sm text-ink-faint">Zone: {PROJECTOR_LABELS[card.location]}</p></div><span className={cn("chip",card.status==="AVAILABLE"?"bg-green-100 text-green-700":card.status==="USED"?"bg-red-100 text-red-700":"bg-gray-200 text-gray-700")}>{card.status}</span></div>{card.used_by_group&&<p className="text-sm">Group {card.used_by_group} · {card.used_at?new Date(card.used_at).toLocaleString():"—"}</p>}<div className="grid grid-cols-2 gap-2"><button disabled={busy} className="btn-secondary" onClick={()=>void edit(card)}>Edit</button><button disabled={busy} className="btn-secondary" onClick={()=>void requirements(card)}>Requirements</button><button disabled={busy} className="btn-secondary" onClick={()=>void reset(card)}>Reset NFC</button><button disabled={busy||card.status!=="USED"} className="btn-danger" onClick={()=>void revert(card)}>Revert activation</button></div></Card>)}</div>}
    <Card className="space-y-2"><h2 className="font-semibold">Recent NFC history</h2>{logs.slice(0,30).map(log=><div key={log.log_id} className="border-t border-paper-200 py-2 text-xs"><p className="font-bold">{log.action} · {log.status}</p><p className="text-ink-faint">NFC {log.nfc_id??"—"} · {log.zone_location??"—"} · Group {log.group_id??"—"} · {new Date(log.created_at).toLocaleString()}</p></div>)}</Card>
  </div>;
}
