"use client";
import QRCode from "qrcode";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Card,ErrorBanner,PageTitle,Spinner,SuccessBanner } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
type Source={id:number;source_code:string;source_name:string;source_type:string;stock_quantity:number;claim_cost:number;per_group_claim_limit:number;is_active:boolean;version:number};
type Box={id:number;blind_box_id:string;source_id:number;type:"NORMAL"|"SPECIAL";reward_amount:number;owner_group_id:number|null;status:"AVAILABLE"|"CLAIMED"|"OPENED"|"CANCELLED";claimed_at:string|null;opened_at:string|null;reward_credit_status:"NOT_REQUIRED"|"PENDING"|"APPLIED"|"REVERSED";version:number};
export default function BlindBoxLogPage(){
 const supabase=useMemo(()=>supabaseBrowser(),[]);const [sources,setSources]=useState<Source[]>([]),[boxes,setBoxes]=useState<Box[]>([]),[draftSources,setDraftSources]=useState<Source[]>([]);const [source,setSource]=useState(""),[group,setGroup]=useState(""),[boxId,setBoxId]=useState(""),[type,setType]=useState(""),[status,setStatus]=useState("");const [edit,setEdit]=useState<Box|null>(null),[reason,setReason]=useState(""),[qr,setQr]=useState<{name:string;dataUrl:string}|null>(null);const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{const [s,b]=await Promise.all([supabase.from("blind_box_sources").select("*").order("source_code"),supabase.from("blind_boxes").select("*").order("created_at",{ascending:false}).limit(500)]);if(s.error||b.error)setError((s.error||b.error)?.message??"Unable to load Blind Boxes");setSources((s.data as Source[])??[]);setDraftSources((s.data as Source[])??[]);setBoxes((b.data as Box[])??[]);setLoading(false)},[supabase]);useEffect(()=>{void load()},[load]);
 const visible=boxes.filter(b=>(!source||b.source_id===Number(source))&&(!group||b.owner_group_id===Number(group))&&(!boxId||b.blind_box_id.toLowerCase().includes(boxId.toLowerCase()))&&(!type||b.type===type)&&(!status||b.status===status));
 const patchSource=(id:number,p:Partial<Source>)=>setDraftSources(v=>v.map(s=>s.id===id?{...s,...p}:s));
 async function saveSource(s:Source){setBusy(true);setError(null);const {error}=await supabase.rpc("fn_admin_update_blind_box_source",{p_source_id:s.id,p_stock:s.stock_quantity,p_claim_cost:s.claim_cost,p_claim_limit:s.per_group_claim_limit,p_is_active:s.is_active,p_expected_version:s.version});setBusy(false);if(error)setError(error.message);else{setNotice("Blind Box source updated successfully.");await load()}}
 async function generateQr(s:Source){setBusy(true);setError(null);try{const res=await fetch("/api/admin/blindbox-source-qr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sourceId:s.id})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Unable to generate QR");setQr({name:s.source_name,dataUrl:await QRCode.toDataURL(data.url,{width:720,margin:2})});setNotice("Source QR generated. Any previous QR for this source is now invalid.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function saveBox(){if(!edit)return;setBusy(true);setError(null);const {error}=await supabase.rpc("fn_admin_correct_blind_box",{p_blind_box_id:edit.blind_box_id,p_type:edit.type,p_status:edit.status,p_reward_amount:edit.reward_amount,p_owner_group_id:edit.owner_group_id,p_credit_status:edit.reward_credit_status,p_expected_version:edit.version,p_reason:reason});setBusy(false);if(error)setError(error.message);else{setNotice("Blind Box updated successfully.");setEdit(null);setReason("");await load()}}
 if(loading)return <div className="flex justify-center py-12"><Spinner/></div>;
 return <div className="space-y-4"><PageTitle title="Blind Box Log" subtitle="Sources, secure QR codes, hidden rewards and corrections"/><ErrorBanner message={error}/><SuccessBanner message={notice}/>
 <Card className="space-y-2"><h2 className="font-semibold">Sources ({sources.length})</h2><div className="max-h-80 space-y-2 overflow-y-auto">{draftSources.map(s=><div key={s.id} className="rounded-xl border border-paper-200 p-3"><div className="flex justify-between"><p className="font-semibold">{s.source_code} · {s.source_name}</p><label className="text-xs"><input type="checkbox" checked={s.is_active} onChange={e=>patchSource(s.id,{is_active:e.target.checked})}/> Active</label></div><div className="mt-2 grid grid-cols-3 gap-2"><label className="text-xs">Stock<input className="input mt-1" type="number" min="0" value={s.stock_quantity} onChange={e=>patchSource(s.id,{stock_quantity:Number(e.target.value)})}/></label><label className="text-xs">Claim cost<input className="input mt-1" type="number" min="0" value={s.claim_cost} onChange={e=>patchSource(s.id,{claim_cost:Number(e.target.value)})}/></label><label className="text-xs">Limit<input className="input mt-1" type="number" min="0" value={s.per_group_claim_limit} onChange={e=>patchSource(s.id,{per_group_claim_limit:Number(e.target.value)})}/></label></div><div className="mt-2 grid grid-cols-2 gap-2"><button className="btn-secondary" disabled={busy} onClick={()=>saveSource(s)}>Save source</button><button className="btn-primary" disabled={busy} onClick={()=>generateQr(s)}>Generate QR</button></div></div>)}</div></Card>
 <Card className="space-y-2"><h2 className="font-semibold">Filter</h2><div className="grid grid-cols-2 gap-2"><select className="input" value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources</option>{sources.map(s=><option key={s.id} value={s.id}>{s.source_code}</option>)}</select><input className="input" type="number" placeholder="Group ID" value={group} onChange={e=>setGroup(e.target.value)}/><input className="input" placeholder="Blind Box ID" value={boxId} onChange={e=>setBoxId(e.target.value)}/><select className="input" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option>NORMAL</option><option>SPECIAL</option></select><select className="input col-span-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>AVAILABLE</option><option>CLAIMED</option><option>OPENED</option><option>CANCELLED</option></select></div></Card>
 <section className="space-y-2"><h2 className="font-semibold">Results ({visible.length})</h2>{visible.map(b=><Card key={b.id} className="p-4"><div className="flex items-start justify-between"><div><p className="font-bold">{b.blind_box_id}</p><p className="text-sm text-ink-soft">Group: {b.owner_group_id??"—"} · Source: {sources.find(s=>s.id===b.source_id)?.source_code}</p><p className="text-sm">{b.type} · Reward: {b.reward_amount} · {b.status}</p><p className="text-xs text-ink-faint">Credit: {b.reward_credit_status}</p></div><button className="btn-secondary px-4" onClick={()=>{setEdit({...b});setReason("")}}>Edit</button></div></Card>)}</section>
 {edit&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/40 p-3 sm:items-center"><Card className="w-full max-w-md space-y-3 p-5"><h2 className="font-bold">Correct {edit.blind_box_id}</h2><div className="grid grid-cols-2 gap-2"><select className="input" value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value as Box["type"]})}><option>NORMAL</option><option>SPECIAL</option></select><select className="input" value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value as Box["status"]})}><option>AVAILABLE</option><option>CLAIMED</option><option>OPENED</option><option>CANCELLED</option></select><input className="input" type="number" min="0" value={edit.reward_amount} onChange={e=>setEdit({...edit,reward_amount:Number(e.target.value)})}/><input className="input" type="number" placeholder="Owner group" value={edit.owner_group_id??""} onChange={e=>setEdit({...edit,owner_group_id:e.target.value?Number(e.target.value):null})}/><select className="input col-span-2" value={edit.reward_credit_status} onChange={e=>setEdit({...edit,reward_credit_status:e.target.value as Box["reward_credit_status"]})}><option>NOT_REQUIRED</option><option>PENDING</option><option>APPLIED</option><option>REVERSED</option></select></div><textarea className="input min-h-20" placeholder="Correction reason (required)" value={reason} onChange={e=>setReason(e.target.value)}/><div className="flex gap-2"><button className="btn-secondary flex-1" onClick={()=>setEdit(null)}>Cancel</button><button className="btn-primary flex-1" disabled={busy||!reason.trim()} onClick={saveBox}>Save correction</button></div></Card></div>}
 {qr&&<div className="fixed inset-0 z-[95] flex items-center justify-center bg-black/60 p-4"><Card className="max-w-sm p-5 text-center"><h2 className="mb-3 font-bold">{qr.name}</h2><img src={qr.dataUrl} alt={`${qr.name} source QR`} className="w-full"/><p className="mt-3 text-xs text-ink-faint">Print or save this QR now. Generating another invalidates this copy.</p><div className="mt-3 grid grid-cols-2 gap-2"><button className="btn-secondary" onClick={()=>setQr(null)}>Close</button><button className="btn-primary" onClick={()=>window.print()}>Print</button></div></Card></div>}
 </div>}
