"use client";

import { Gift, QrCode, Sparkles } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { BlindBoxQrScanner } from "@/components/BlindBoxQrScanner";
import { useCurrentUserContext } from "@/components/ProfileProvider";
import { useToast } from "@/components/ToastProvider";
import { Card, Spinner } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { cn, friendlyError, idemKey } from "@/lib/utils";

interface GroupBlindBox { blind_box_id:string;type:"NORMAL"|"SPECIAL";status:"CLAIMED"|"OPENED";claimed_at:string;opened_at:string|null;reward_amount:number|null;reward_credit_status:string }

export function BlindBoxInventory(){
  const supabase=useMemo(()=>supabaseBrowser(),[]),toast=useToast(),router=useRouter(),searchParams=useSearchParams(),currentUser=useCurrentUserContext();
  const canClaim=currentUser.role==="faci"&&currentUser.permissions.includes("blindbox.claim"),canOpen=currentUser.role==="faci"&&currentUser.permissions.includes("blindbox.open");
  const [boxes,setBoxes]=useState<GroupBlindBox[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const [scannerOpen,setScannerOpen]=useState(false),[selectedBox,setSelectedBox]=useState<GroupBlindBox|null>(null),[reward,setReward]=useState<number|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);const {data,error:e}=await supabase.rpc("fn_group_blind_boxes");if(e)setError(friendlyError(e));else setBoxes((data as GroupBlindBox[])??[]);setLoading(false)},[supabase]);
  useEffect(()=>{void load();const recover=()=>void load();window.addEventListener("orientation:reconnect",recover);return()=>window.removeEventListener("orientation:reconnect",recover)},[load]);
  const claimToken=useCallback(async(token:string)=>{setScannerOpen(false);setBusy(true);setError(null);try{const response=await fetch("/api/blindbox/source-claim",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,requestId:idemKey()})}),data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to claim Blind Box");toast({message:"Blind Box obtained successfully.",tone:"success"});await load()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}},[load,toast]);
  useEffect(()=>{const token=searchParams.get("blindbox_source");if(token){if(canClaim)void claimToken(token);router.replace("/inventory")}},[canClaim,claimToken,router,searchParams]);
  async function openBox(){if(!selectedBox)return;setBusy(true);setError(null);const {data,error:e}=await supabase.rpc("fn_open_blind_box",{p_blind_box_id:selectedBox.blind_box_id,p_request_id:idemKey()});setBusy(false);if(e){setError(friendlyError(e));return}const amount=Number((data as {reward_amount:number}).reward_amount);setSelectedBox(null);setReward(amount);toast({message:`Your group received ${amount} tokens.`,tone:"success"});await load()}
  return <><Card><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Blind Box</h2><p className="text-xs text-ink-faint">{boxes.filter(box=>box.status==="CLAIMED").length} unopened</p></div>{canClaim&&<button disabled={busy} className="btn-primary px-4" onClick={()=>setScannerOpen(true)}><QrCode size={18}/>Scan</button>}</div>{loading?<div className="flex min-h-[112px] items-center justify-center"><Spinner/></div>:error?<><p className="py-3 text-sm font-semibold text-red-700">{error}</p><button className="btn-secondary w-full" onClick={()=>void load()}>Retry Blind Box</button></>:<><div className="grid grid-cols-4 gap-2">{boxes.map(box=><button key={box.blind_box_id} disabled={!canOpen||box.status!=="CLAIMED"} onClick={()=>setSelectedBox(box)} className={cn("aspect-square rounded-2xl border p-2",box.status==="CLAIMED"?"border-brand-1/30 bg-brand-1/10 text-brand-1":"border-paper-200 bg-paper-100 text-ink-faint")} aria-label={`${box.type} Blind Box ${box.status}`}><Gift className="mx-auto"/><span className="mt-1 block text-[10px] font-bold">{box.status==="OPENED"?`+${box.reward_amount}`:box.type}</span></button>)}</div>{boxes.length===0&&<p className="py-6 text-center text-sm text-ink-faint">No Blind Boxes claimed yet.</p>}{!canOpen&&boxes.length>0&&<p className="mt-3 text-center text-xs text-ink-faint">Your Faci handles Blind Box scanning and opening.</p>}</>}</Card>{canClaim&&<BlindBoxQrScanner open={scannerOpen} onResult={claimToken} onClose={()=>setScannerOpen(false)}/>} {canOpen&&selectedBox&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/40 p-3 sm:items-center"><Card className="w-full max-w-sm space-y-4 p-6 text-center"><h2 className="text-xl font-bold">Blind Box</h2><Gift className="mx-auto h-20 w-20 text-brand-1"/><p className="text-sm text-ink-faint">The stored reward will be revealed once.</p><button disabled={busy} className="btn-primary w-full" onClick={()=>void openBox()}>{busy?"Opening…":"Open Blind Box"}</button><button className="btn-secondary w-full" onClick={()=>setSelectedBox(null)}>Cancel</button></Card></div>}{reward!==null&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/40 p-3"><Card className="w-full max-w-sm space-y-4 p-7 text-center"><Sparkles className="mx-auto h-16 w-16 text-amber-500"/><h2 className="text-xl font-bold">Reward</h2><p className="text-3xl font-black text-brand-1">+ {reward} tokens</p><button className="btn-primary w-full" onClick={()=>setReward(null)}>OK</button></Card></div>}</>;
}
