#!/usr/bin/env bash
# Per-boot startup for the XMUM Orientation Platform local dev stack.
#
# Brings up the Docker daemon and the Supabase local stack (Postgres, Auth,
# PostgREST, Realtime, Storage), applies migrations, writes .env.local, and
# seeds demo accounts. Idempotent: safe to run against an already-running stack.
# The Next.js dev server itself runs as a `terminals` entry so its logs stay
# visible and it can be restarted independently.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

log() { echo "[start] $*"; }

# ── 1. Docker daemon ──────────────────────────────────────────────────────────
# Launch dockerd in its own session (setsid + detached stdio) so it survives
# after this start command returns; a plain background job can be reaped when
# the start command's process group is cleaned up, leaving a dead daemon.
if ! sudo docker info >/dev/null 2>&1; then
  log "Starting Docker daemon..."
  # Open the log with the current (non-root) shell so the redirect works even
  # on fuse-backed /tmp, and wrap in setsid so dockerd keeps running in its own
  # session after this start command's process group is cleaned up.
  sudo rm -f /tmp/dockerd.log 2>/dev/null || true
  setsid sudo dockerd >/tmp/dockerd.log 2>&1 </dev/null &
  for _ in $(seq 1 60); do
    sudo docker info >/dev/null 2>&1 && break
    sleep 1
  done
fi
sudo chmod 666 /var/run/docker.sock 2>/dev/null || true
if ! sudo docker info >/dev/null 2>&1; then
  log "ERROR: Docker daemon failed to start; see /tmp/dockerd.log"
  exit 1
fi
log "Docker ready: $(docker --version)"

# ── 2. Supabase local stack ───────────────────────────────────────────────────
# `supabase start` can lose a first-boot race where supabase_db is still
# "starting"; it is idempotent, so retry until the stack reports healthy.
if supabase status >/dev/null 2>&1; then
  log "Supabase already running."
else
  log "Starting Supabase local stack (applies migrations)..."
  for attempt in 1 2 3 4 5; do
    supabase start && break
    log "supabase start attempt ${attempt} did not complete (db readiness race?); retrying in 10s..."
    sleep 10
  done
fi
if ! supabase status >/dev/null 2>&1; then
  log "ERROR: Supabase stack failed to become ready; see 'supabase status'."
  exit 1
fi
log "Supabase stack is up."

# ── 3. Environment file for the Next.js app ───────────────────────────────────
# Local Supabase keys are deterministic dev credentials, not real secrets.
API_URL="$(supabase status -o env 2>/dev/null | grep -oP '^API_URL="\K[^"]+')"
ANON_KEY="$(supabase status -o env 2>/dev/null | grep -oP '^ANON_KEY="\K[^"]+')"
SERVICE_KEY="$(supabase status -o env 2>/dev/null | grep -oP '^SERVICE_ROLE_KEY="\K[^"]+')"

if [ ! -f .env.local ]; then
  log "Writing .env.local..."
  cat > .env.local <<EOF
# Local development — Supabase CLI local stack (generated by .cursor/start.sh)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
NFC_TOKEN_SECRET=$(openssl rand -hex 32)
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF
else
  log ".env.local already exists; leaving it untouched."
fi

# ── 4. Seed demo/test accounts (idempotent upsert) ────────────────────────────
log "Seeding demo accounts..."
node --env-file=.env.local scripts/seed-test-accounts.mjs || \
  log "Seeding skipped/failed (non-fatal)."

log "start.sh complete. Supabase Studio: http://localhost:54323"
