#!/usr/bin/env bash
# Per-boot startup for the XMUM Orientation Platform local dev stack.
#
# Brings up the Docker daemon and the Supabase local stack (Postgres, Auth,
# PostgREST, Realtime, Storage), applies migrations, writes .env.local, and
# seeds demo accounts. Idempotent: safe to run against an already-running stack.
# The Next.js dev server itself runs as a `terminals` entry so its logs stay
# visible and it can be restarted independently.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

log() { echo "[start] $*"; }

# ── 1. Docker daemon ──────────────────────────────────────────────────────────
if ! sudo docker info >/dev/null 2>&1; then
  log "Starting Docker daemon..."
  sudo dockerd >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 60); do
    sudo docker info >/dev/null 2>&1 && break
    sleep 1
  done
fi
sudo chmod 666 /var/run/docker.sock 2>/dev/null || true
log "Docker ready: $(docker --version)"

# ── 2. Supabase local stack ───────────────────────────────────────────────────
if supabase status >/dev/null 2>&1; then
  log "Supabase already running."
else
  log "Starting Supabase local stack (applies migrations)..."
  supabase start
fi

# ── 3. Environment file for the Next.js app ───────────────────────────────────
# Local Supabase keys are deterministic dev credentials, not real secrets.
API_URL="$(supabase status -o env 2>/dev/null | grep -oP '^API_URL="\K[^"]+')"
ANON_KEY="$(supabase status -o env 2>/dev/null | grep -oP '^ANON_KEY="\K[^"]+')"
SERVICE_KEY="$(supabase status -o env 2>/dev/null | grep -oP '^SERVICE_ROLE_KEY="\K[^"]+')"

if [ ! -f .env.local ]; then
  log "Writing .env.local..."
  cat > .env.local <<EOF
# Local development — Supabase CLI local stack (generated by .cursor/start.sh)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
NFC_TOKEN_SECRET=$(openssl rand -hex 32)
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF
else
  log ".env.local already exists; leaving it untouched."
fi

# ── 4. Seed demo/test accounts (idempotent upsert) ────────────────────────────
log "Seeding demo accounts..."
node --env-file=.env.local scripts/seed-test-accounts.mjs || \
  log "Seeding skipped/failed (non-fatal)."

log "start.sh complete. Supabase Studio: http://localhost:54323"
