"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useCurrentUserContext} from "@/components/ProfileProvider";
import {Card,ErrorBanner,PageTitle,Spinner,SuccessBanner} from "@/components/ui";
import {supabaseBrowser} from "@/lib/supabase/client";
import type {Station} from "@/lib/types";
import {cn,friendlyError} from "@/lib/utils";
type Setting={key:string;value:unknown;version:number};type Tab="GENERAL"|"BLIND_BOX"|"LIGHTING";
const GAME_KEYS=[["day1_win_reward","Day 1 win reward"],["day1_lose_reward","Day 1 lose reward"],["max_station_attempts","Maximum station attempts"],["bonding_session_duration_day1","Day 1 duration (minutes)"],["bonding_session_duration_day2","Day 2 duration (minutes)"]] as const;
const BOX_KEYS=[["blind_box_gm_claim_cost","GM claim cost"],["blind_box_normal_reward_min","Normal minimum"],["blind_box_normal_reward_max","Normal maximum"],["blind_box_special_reward_min","Special minimum"],["blind_box_special_reward_max","Special maximum"],["blind_box_gm_total_claim_limit","GM total claim limit"],["blind_box_source_claim_limit","Per-source claim limit"],["blind_box_oc_team_default_stock","OC Team default stock"],["blind_box_hof_default_stock","HOF default stock"],["blind_box_hogm_default_stock","HOGM default stock"],["blind_box_gm_station_default_stock","GM station default stock"]] as const;
export default function ConfigurationPage(){const context=useCurrentUserContext(),isTech=context.role==="admin",supabase=useMemo(()=>supabaseBrowser(),[]);const[tab,setTab]=useState<Tab>("GENERAL"),[settings,setSettings]=useState<Setting[]>([]),[draft,setDraft]=useState<Record<string,string>>({}),[stations,setStations]=useState<Station[]>([]),[originalStations,setOriginalStations]=useState<Station[]>([]);const[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
const load=useCallback(async()=>{setLoading(true);const[a,b]=await Promise.all([supabase.from("game_config").select("key,value,version"),supabase.from("stations").select("*").order("station_number")]);if(a.error||b.error)setError(friendlyError(a.error||b.error));const rows=(a.data as Setting[])??[],values=Object.fromEntries(rows.map(x=>[x.key,String(x.value).replace(/^"|"$/g,"")]));if(!values.bonding_session_duration_day1)values.bonding_session_duration_day1=values.bonding_session_duration??"150";if(!values.bonding_session_duration_day2)values.bonding_session_duration_day2=values.bonding_session_duration??"150";setSettings(rows);setDraft(values);const stationRows=((b.data as Station[])??[]).map(s=>({...s,difficulty:s.difficulty==="NONE"?"EASY":s.difficulty}));setStations(stationRows);setOriginalStations(stationRows);setLoading(false)},[supabase]);useEffect(()=>{void load()},[load]);
const setting=(key:string)=>settings.find(x=>x.key===key);const changed=(keys:readonly(readonly[string,string])[])=>keys.some(([key])=>draft[key]!==String(setting(key)?.value??(key.includes("duration_day")?draft.bonding_session_duration??"150":"")).replace(/^"|"$/g,""));
async function writeSetting(key:string,value:unknown){const row=setting(key);const{error:e}=await supabase.rpc("fn_admin_set_game_setting",{p_key:key,p_value:value,p_expected_version:row?.version??0,p_reason:"Grouped configuration update"});if(e)throw e}
async function saveSettings(name:string,keys:readonly(readonly[string,string])[]){setBusy(name);setError(null);try{for(const[key]of keys)await writeSetting(key,Number(draft[key]));setNotice(`${name} saved successfully.`);await load()}catch(e){setError(friendlyError(e))}finally{setBusy(null)}}
async function saveGameplay(){setBusy("gameplay");setError(null);try{for(const[key]of GAME_KEYS)await writeSetting(key,Number(draft[key]));await writeSetting("allow_station_replay",draft.allow_station_replay==="true");for(const s of stations.filter(x=>!x.day||x.day===2)){const original=originalStations.find(x=>x.id===s.id);if(JSON.stringify(s)!==JSON.stringify(original)){const{error:e}=await supabase.rpc("fn_admin_set_station_config",{p_station_id:s.id,p_difficulty:s.difficulty??"EASY",p_token_cost:s.token_cost??0,p_exclusion_limit:s.location_exclusion_limit??0,p_is_active:s.is_active??true,p_expected_version:s.config_version??1,p_reason:"Grouped gameplay configuration update"});if(e)throw e}}setNotice("Gameplay, replay policy and Day 2 stations saved.");await load()}catch(e){setError(friendlyError(e))}finally{setBusy(null)}}
async function saveLighting(){setBusy("lighting");setError(null);try{await writeSetting("lighting_effect_scope",draft.lighting_effect_scope??"ALL_VIEWERS");await writeSetting("lighting_effect_style",draft.lighting_effect_style??"GLOW");await writeSetting("lighting_effect_duration_ms",Number(draft.lighting_effect_duration_ms??2400));setNotice("Lighting settings saved.");await load()}catch(e){setError(friendlyError(e))}finally{setBusy(null)}}
const patchStation=(id:number,p:Partial<Station>)=>setStations(v=>v.map(s=>s.id===id?{...s,...p}:s));const stationsDirty=JSON.stringify(stations)!==JSON.stringify(originalStations),gameDirty=changed(GAME_KEYS)||draft.allow_station_replay!==String(setting("allow_station_replay")?.value??false)||stationsDirty,boxDirty=changed(BOX_KEYS);if(loading)return <div className="flex justify-center py-12"><Spinner/></div>;const tabs:[Tab,string][]=[["GENERAL","General & gameplay"],["BLIND_BOX","Blind Box"],["LIGHTING","NFC & Lighting"]];
return <div className="space-y-4"><PageTitle title="Configuration" subtitle="Grouped current-orientation settings"/><ErrorBanner message={error}/><SuccessBanner message={notice}/><div className="flex gap-2 overflow-x-auto pb-1">{tabs.filter(([key])=>isTech||key==="GENERAL").map(([key,label])=><button key={key} className={cn("whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold",tab===key?"bg-ink text-white":"bg-white text-ink-soft shadow-card")} onClick={()=>setTab(key)}>{label}</button>)}</div>
{tab==="GENERAL"&&<><Card className="space-y-3"><h2 className="font-semibold uppercase">Gameplay and session</h2><p className="text-xs text-ink-faint">Day 1 and Day 2 durations are independent. Save once after reviewing the complete section.</p>{GAME_KEYS.map(([key,label])=><label key={key} className="grid grid-cols-[1fr_7rem] items-center gap-3 text-sm"><span>{label}</span><input type="number" min="0" className="input" value={draft[key]??""} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<div className="grid grid-cols-2 gap-2"><button className={draft.allow_station_replay==="true"?"btn-primary":"btn-secondary"} onClick={()=>setDraft({...draft,allow_station_replay:"true"})}>Allow replay</button><button className={draft.allow_station_replay!=="true"?"btn-primary":"btn-secondary"} onClick={()=>setDraft({...draft,allow_station_replay:"false"})}>One attempt</button></div></Card><Card className="space-y-3"><h2 className="font-semibold uppercase">Day 2 stations</h2>{stations.filter(s=>!s.day||s.day===2).map(s=><div key={s.id} className="rounded-xl border border-paper-200 p-3"><p className="mb-2 font-semibold">{s.code} · {s.name}</p><div className="grid grid-cols-2 gap-2"><label className="text-xs">Difficulty<select className="input mt-1" value={s.difficulty??"EASY"} onChange={e=>patchStation(s.id,{difficulty:e.target.value as Station["difficulty"]})}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><label className="text-xs">Entry cost<input type="number" min="0" className="input mt-1" value={s.token_cost??0} onChange={e=>patchStation(s.id,{token_cost:Number(e.target.value)})}/></label><label className="text-xs">Exclusion limit<input type="number" min="0" className="input mt-1" value={s.location_exclusion_limit??0} onChange={e=>patchStation(s.id,{location_exclusion_limit:Number(e.target.value)})}/></label><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={s.is_active??true} onChange={e=>patchStation(s.id,{is_active:e.target.checked})}/>Active</label></div></div>)}<button className="btn-primary w-full disabled:cursor-not-allowed disabled:opacity-40" disabled={busy!==null||!gameDirty} onClick={()=>void saveGameplay()}>{busy==="gameplay"?"Saving…":"Save gameplay & stations"}</button></Card></>}
{tab==="BLIND_BOX"&&isTech&&<Card className="space-y-3"><h2 className="font-semibold uppercase">Blind Box settings</h2>{BOX_KEYS.map(([key,label])=><label key={key} className="grid grid-cols-[1fr_7rem] items-center gap-3 text-sm"><span>{label}</span><input type="number" min="0" className="input" value={draft[key]??""} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<button className="btn-primary w-full disabled:cursor-not-allowed disabled:opacity-40" disabled={busy!==null||!boxDirty} onClick={()=>void saveSettings("Blind Box settings",BOX_KEYS)}>{busy==="Blind Box settings"?"Saving…":"Save Blind Box settings"}</button><a href="/admin/blindbox" className="btn-secondary flex w-full justify-center">Open QR generation</a></Card>}
{tab==="LIGHTING"&&isTech&&<Card className="space-y-3"><h2 className="font-semibold uppercase">NFC and Lighting Zone effects</h2><label className="block text-sm">Effect devices<select className="input mt-1" value={draft.lighting_effect_scope??"ALL_VIEWERS"} onChange={e=>setDraft({...draft,lighting_effect_scope:e.target.value})}><option value="SCANNING_DEVICE">Scanning device only</option><option value="ALL_VIEWERS">All connected viewers</option><option value="NONE">No effect</option></select></label><label className="block text-sm">Effect style<select className="input mt-1" value={draft.lighting_effect_style??"GLOW"} onChange={e=>setDraft({...draft,lighting_effect_style:e.target.value})}><option value="GLOW">Glow celebration</option><option value="PULSE">Pulse celebration</option><option value="NONE">No visual effect</option></select></label><label className="block text-sm">Duration (milliseconds)<input type="number" min="0" max="10000" className="input mt-1" value={draft.lighting_effect_duration_ms??"2400"} onChange={e=>setDraft({...draft,lighting_effect_duration_ms:e.target.value})}/></label><button className="btn-primary w-full" disabled={busy!==null} onClick={()=>void saveLighting()}>{busy==="lighting"?"Saving…":"Save NFC & Lighting settings"}</button><a href="/admin/nfc" className="btn-secondary flex w-full justify-center">Open NFC cards</a></Card>}
</div>}
