"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Card,ErrorBanner,PageTitle,Spinner,SuccessBanner } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import type { Station } from "@/lib/types";

type Setting={key:string;value:unknown;version:number};
const GROUPS=[
 {title:"Day 1 token settings",keys:[["day1_win_reward","Win reward"],["day1_lose_reward","Lose reward"]]},
 {title:"Blind Box settings",keys:[["blind_box_gm_claim_cost","GM claim cost"],["blind_box_normal_reward_min","Normal minimum"],["blind_box_normal_reward_max","Normal maximum"],["blind_box_special_reward_min","Special minimum"],["blind_box_special_reward_max","Special maximum"],["blind_box_gm_total_claim_limit","GM total claim limit"],["blind_box_source_claim_limit","Per-source claim limit"],["blind_box_oc_team_default_stock","OC Team default stock"],["blind_box_hof_default_stock","HOF default stock"],["blind_box_hogm_default_stock","HOGM default stock"],["blind_box_gm_station_default_stock","GM station default stock"]]},
 {title:"Session settings",keys:[["bonding_session_duration","Duration (minutes)"],["max_station_attempts","Maximum station attempts"]]},
] as const;
export default function ConfigurationPage(){const supabase=useMemo(()=>supabaseBrowser(),[]);const [settings,setSettings]=useState<Setting[]>([]),[draft,setDraft]=useState<Record<string,string>>({}),[stations,setStations]=useState<Station[]>([]);const [loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{const [a,b]=await Promise.all([supabase.from("game_config").select("key,value,version"),supabase.from("stations").select("*").order("station_number")]);if(a.error||b.error)setError((a.error||b.error)?.message??"Unable to load configuration");const rows=(a.data as Setting[])??[];setSettings(rows);setDraft(Object.fromEntries(rows.map(x=>[x.key,String(x.value)])));setStations(((b.data as Station[])??[]).map(s=>({...s,difficulty:s.difficulty==="NONE"?"EASY":s.difficulty})));setLoading(false)},[supabase]);useEffect(()=>{void load()},[load]);
 async function saveSetting(key:string){const row=settings.find(x=>x.key===key);if(!row)return;setBusy(key);setError(null);const value=Number(draft[key]);const {error}=await supabase.rpc("fn_admin_set_game_setting",{p_key:key,p_value:value,p_expected_version:row.version,p_reason:"Admin configuration page"});setBusy(null);if(error)setError(error.message.includes("CONFLICT")?"This setting was changed by another Admin. Refresh and try again.":error.message);else{setNotice("Configuration updated successfully.");await load();}}
 async function saveStation(s:Station){setBusy(`station-${s.id}`);setError(null);const {error}=await supabase.rpc("fn_admin_set_station_config",{p_station_id:s.id,p_difficulty:s.difficulty??"EASY",p_token_cost:s.token_cost??0,p_exclusion_limit:s.location_exclusion_limit??0,p_is_active:s.is_active??true,p_expected_version:s.config_version??1,p_reason:"Admin configuration page"});setBusy(null);if(error)setError(error.message);else{setNotice("Station configuration updated successfully.");await load();}}
 const patchStation=(id:number,p:Partial<Station>)=>setStations(v=>v.map(s=>s.id===id?{...s,...p}:s));
 if(loading)return <div className="flex justify-center py-12"><Spinner/></div>;
 return <div className="space-y-4"><PageTitle title="Configuration" subtitle="Current orientation gameplay values"/><ErrorBanner message={error}/><SuccessBanner message={notice}/>{GROUPS.map(g=><Card key={g.title} className="space-y-3"><h2 className="font-semibold uppercase">{g.title}</h2>{g.keys.map(([key,label])=><label key={key} className="grid grid-cols-[1fr_7rem] items-center gap-3 text-sm"><span>{label}</span><input type="number" min="0" className="input" value={draft[key]??""} onChange={e=>setDraft({...draft,[key]:e.target.value})}/><button className="btn-secondary col-span-2" disabled={busy===key} onClick={()=>saveSetting(key)}>{busy===key?"Saving…":"Save"}</button></label>)}</Card>)}
 <Card className="space-y-3"><h2 className="font-semibold uppercase">Day 2 stations</h2>{stations.filter(s=>!s.day||s.day===2).map(s=><div key={s.id} className="rounded-xl border border-paper-200 p-3"><p className="mb-2 font-semibold">{s.code} · {s.name}</p><div className="grid grid-cols-2 gap-2"><label className="text-xs">Difficulty<select className="input mt-1" value={s.difficulty??"EASY"} onChange={e=>patchStation(s.id,{difficulty:e.target.value as Station["difficulty"]})}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><label className="text-xs">Entry cost<input type="number" min="0" className="input mt-1" value={s.token_cost??0} onChange={e=>patchStation(s.id,{token_cost:Number(e.target.value)})}/></label><label className="text-xs">Exclusion limit<input type="number" min="0" className="input mt-1" value={s.location_exclusion_limit??0} onChange={e=>patchStation(s.id,{location_exclusion_limit:Number(e.target.value)})}/></label><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={s.is_active??true} onChange={e=>patchStation(s.id,{is_active:e.target.checked})}/> Active</label></div><button className="btn-primary mt-3 w-full" disabled={busy===`station-${s.id}`} onClick={()=>saveStation(s)}>Save station</button></div>)}</Card></div>}
